# Generated by Django 3.2.6 on 2021-09-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_no',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
