# Generated by Django 3.2.6 on 2021-11-08 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer_table',
            name='ques_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ques_idd', to='database.ques_table'),
        ),
        migrations.AlterField(
            model_name='ques_table',
            name='correct',
            field=models.IntegerField(),
        ),
    ]
