# Generated by Django 3.2.6 on 2021-11-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20211108_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='score_table',
            name='percentage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
