# Generated by Django 3.2.6 on 2021-11-10 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_score_table_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_details',
            name='class_stu',
            field=models.IntegerField(default=11),
        ),
        migrations.AddField(
            model_name='user',
            name='role_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='database.role_id'),
        ),
    ]
