# Generated by Django 3.2.6 on 2021-11-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20211110_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_details',
            name='date',
            field=models.DateField(help_text='YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='score_table',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
