# Generated by Django 3.2.6 on 2021-11-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20211114_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_id',
            name='class_stu_tech',
            field=models.IntegerField(default=11),
        ),
        migrations.AlterField(
            model_name='exam_details',
            name='date',
            field=models.DateField(help_text='(YYYY-MM-DD)'),
        ),
    ]
